version: "3.3"

services:

  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env

    depends_on:
      - postgres
      - redis
      - rabbitmq

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ops_platform
      DB_USER: postgres
      DB_PASSWORD: postgres

      REDIS_HOST: redis

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

    command: npm run dev

  postgres:
    image: postgres:15

    environment:
      POSTGRES_DB: ops_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  redis:
    image: redis:7

    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management

    ports:
      - "5672:5672"
      - "15672:15672"